export enum ProductCategory {
  // VERDULERÍA
  FRUIT = "FRUIT",
  VEGETABLE = "VEGETABLE",
  HERBS = "HERBS",
  TUBER = "TUBER",
  SEEDLING = "SEEDLING",
  // PANADERÍA
  BREAD = "BREAD",
  PASTRIES = "PASTRIES",
  CAKES = "CAKES",
  COOKIES = "COOKIES",
  DOUGH = "DOUGH",
  DESSERTS_BAKERY = "DESSERTS_BAKERY",
  // RESTAURANTE
  APPETIZERS = "APPETIZERS",
  MAIN_COURSES = "MAIN_COURSES",
  DESSERTS_RESTAURANT = "DESSERTS_RESTAURANT",
  BEVERAGES_RESTAURANT = "BEVERAGES_RESTAURANT",
  // KIOSCO/SUPERMERCADO
  CLEANING = "CLEANING",
  BEVERAGES = "BEVERAGES",
  GROCERIES = "GROCERIES",
  FRESH_PRODUCTS = "FRESH_PRODUCTS",
  FROZEN = "FROZEN",
  PERSONAL_HYGIENE = "PERSONAL_HYGIENE",
  CANDY = "CANDY",
  SNACKS = "SNACKS",
  CIGARETTES = "CIGARETTES",
  MAGAZINES = "MAGAZINES",
  // CROSS
  GREENGROCERY_SECTION = "GREENGROCERY_SECTION",
  BAKERY_SECTION = "BAKERY_SECTION",
  // OTHER
  OTHER = "OTHER",
}

export const ProductCategoryDisplayName: Record<ProductCategory, string> = {
  [ProductCategory.FRUIT]: "Fruta",
  [ProductCategory.VEGETABLE]: "Verdura",
  [ProductCategory.HERBS]: "Hierbas",
  [ProductCategory.TUBER]: "Tubérculo",
  [ProductCategory.SEEDLING]: "Plantines",
  [ProductCategory.BREAD]: "Pan",
  [ProductCategory.PASTRIES]: "Facturas",
  [ProductCategory.CAKES]: "Tortas",
  [ProductCategory.COOKIES]: "Galletas",
  [ProductCategory.DOUGH]: "Masas",
  [ProductCategory.DESSERTS_BAKERY]: "Postres (Panadería)",
  [ProductCategory.APPETIZERS]: "Entradas",
  [ProductCategory.MAIN_COURSES]: "Platos Principales",
  [ProductCategory.DESSERTS_RESTAURANT]: "Postres (Restaurante)",
  [ProductCategory.BEVERAGES_RESTAURANT]: "Bebidas (Restaurante)",
  [ProductCategory.CLEANING]: "Limpieza",
  [ProductCategory.BEVERAGES]: "Bebidas",
  [ProductCategory.GROCERIES]: "Comestibles",
  [ProductCategory.FRESH_PRODUCTS]: "Frescos",
  [ProductCategory.FROZEN]: "Congelados",
  [ProductCategory.PERSONAL_HYGIENE]: "Higiene Personal",
  [ProductCategory.CANDY]: "Golosinas",
  [ProductCategory.SNACKS]: "Snacks",
  [ProductCategory.CIGARETTES]: "Cigarrillos",
  [ProductCategory.MAGAZINES]: "Revistas",
  [ProductCategory.GREENGROCERY_SECTION]: "Sección Verdulería",
  [ProductCategory.BAKERY_SECTION]: "Sección Panadería",
  [ProductCategory.OTHER]: "Otro",
};
