// import type { Store, Deal } from "./../interfaces/types";
// import type { ProductTag } from "./../interfaces/types";

// export const stores: Store[] = [
//   {
//     id: 1,
//     name: "Supera",
//     subtitle: "Supermercado de barrio",
//     profileImageUrl: "https://acdn-us.mitiendanube.com/stores/001/252/117/themes/common/logo-1326126770-1594263950-404d77509db5b1747138c82e5a8d257e1594263951.png?0",
//     imageUrl: "https://acdn-us.mitiendanube.com/stores/001/252/117/themes/common/logo-1326126770-1594263950-404d77509db5b1747138c82e5a8d257e1594263951.png?0",
//     location: "Av. San Martín 1234, Centro",
//     schedule: "Lun-Vie 8:00-20:00, Sáb 9:00-13:00",
//     deliveryAvailable: true,
//     phoneNumber: "+54 353 123-4567",
//     categories: ["Verduleria"],
//   },
//   {
//     id: 2,
//     name: "La parillada",
//     subtitle: "Restaurante parrilla",
//     profileImageUrl: "https://mir-s3-cdn-cf.behance.net/project_modules/1400/aad4d0110142211.5fe4b63868daa.jpg",
//     imageUrl: "https://mir-s3-cdn-cf.behance.net/project_modules/1400/aad4d0110142211.5fe4b63868daa.jpg",
//     location: "Calle Belgrano 567",
//     schedule: "Lun-Dom 11:00-15:00, 19:00-23:00",
//     deliveryAvailable: true,
//     categories: ["Restaurante"],
//   },
//   {
//     id: 3,
//     name: "Doña Vicky",
//     subtitle: "Verdulería fresca",
//     profileImageUrl: "https://i.pinimg.com/originals/77/1e/03/771e0354d08d3c87c62057137cbad533.jpg",
//     imageUrl: "https://i.pinimg.com/originals/77/1e/03/771e0354d08d3c87c62057137cbad533.jpg",
//     location: "Av. Sabattini 890",
//     schedule: "Mar-Dom 8:00-13:00",
//     deliveryAvailable: true,
//     categories: ["Panaderia"],
//   },
//   {
//     id: 4,
//     name: "Jumbo",
//     subtitle: "Supermercado mayorista",
//     profileImageUrl: "https://e7.pngegg.com/pngimages/573/590/png-clipart-brand-logo-supermarket-jumbo-lider-harvard-business-publishing-text-logo.png",
//     imageUrl: "https://e7.pngegg.com/pngimages/573/590/png-clipart-brand-logo-supermarket-jumbo-lider-harvard-business-publishing-text-logo.png",
//     location: "Shopping Nuestro, Local 45",
//     schedule: "Lun-Dom 9:00-21:00",
//     deliveryAvailable: true,
//     categories: ["Supermercado"],
//   },
//   {
//     id: 5,
//     name: "Kiosco Cartu",
//     subtitle: "Kiosco de barrio",
//     profileImageUrl: "https://lacomuna12.com.ar/images/2021/sociedad/kioscovillaurquiza2.jpg",
//     imageUrl: "https://lacomuna12.com.ar/images/2021/sociedad/kioscovillaurquiza2.jpg",
//     location: "Calle Sarmiento 234",
//     schedule: "Lun-Dom 7:00-23:00",
//     deliveryAvailable: false,
//     categories: ["Kiosco"],
//   },
//   {
//     id: 6,
//     name: "Boston 24hs",
//     subtitle: "Kiosco 24 horas",
//     profileImageUrl: "https://lapiramide.net/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-26-at-17.55.33-e1708981357121.jpeg",
//     imageUrl: "https://lapiramide.net/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-26-at-17.55.33-e1708981357121.jpeg",
//     location: "Av. Colón 789",
//     schedule: "24 horas",
//     deliveryAvailable: true,
//     categories: ["Kiosco"],
//   },
//   {
//     id: 7,
//     name: "Fresh",
//     subtitle: "Verdulería orgánica",
//     profileImageUrl: "https://www.shutterstock.com/image-vector/supermarket-logo-fruit-inside-shopping-260nw-2446378847.jpg",
//     imageUrl: "https://www.shutterstock.com/image-vector/supermarket-logo-fruit-inside-shopping-260nw-2446378847.jpg",
//     location: "Calle 9 de Julio 456",
//     schedule: "Lun-Sáb 8:00-20:00",
//     deliveryAvailable: true,
//     categories: ["Verduleria"],
//   },
//   {
//     id: 8,
//     name: "Home made",
//     subtitle: "Panadería artesanal",
//     profileImageUrl: "https://images.vexels.com/media/users/3/172803/raw/ecfb62e1a465e71be07ac4aa734a2f0a-diseno-de-logo-de-panaderia.jpg",
//     imageUrl: "https://images.vexels.com/media/users/3/172803/raw/ecfb62e1a465e71be07ac4aa734a2f0a-diseno-de-logo-de-panaderia.jpg",
//     location: "Bv. Savio 123",
//     schedule: "Mar-Dom 7:00-13:00",
//     deliveryAvailable: true,
//     categories: ["Panaderia"],
//   },
// ];

// const getDaysUntilExpiration = (expirationDate: string): string => {
//   const today = new Date();
//   const expDate = new Date(expirationDate);
//   const diffTime = expDate.getTime() - today.getTime();
//   const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  
//   if (diffDays <= 0) return "Hoy";
//   if (diffDays === 1) return "1 día";
//   if (diffDays === 2) return "2 días";
//   if (diffDays === 3) return "3 días";
//   if (diffDays === 4) return "4 días";
//   if (diffDays <= 7) return `${diffDays} días`;
//   if (diffDays <= 14) return "una semana";
//   if (diffDays <= 30) return `${Math.ceil(diffDays / 7)} semanas`;
//   return "un mes o más";
// };

// export const deals: Deal[] = [
//   {
//     id: 1,
//     title: "Pan para rallar",
//     description: "Pan del día anterior ideal para hacer pan rallado casero. Producto en perfecto estado de conservación.",
//     imageUrl: "https://cocinerosargentinos.com/content/recipes/500x500/recipes.20819.jpg",
//     price: 250,
//     originalPrice: 357,
//     discount: 30,
//     stock: 8,
//     expirationDate: "2026-11-20T00:00:00",
//     expiresIn: getDaysUntilExpiration("2026-11-20T00:00:00"),
//     category: "Panadería",
//     productType: "Pan",
//     storeId: 8,
//     tags: ["buen-estado", "vegetariano"],
//   },
//   {
//     id: 2,
//     title: "Duraznos para mermelada",
//     description: "Duraznos maduros perfectos para hacer mermeladas, compotas o conservas. Frutas orgánicas de producción local.",
//     imageUrl: "https://i.ytimg.com/vi/IqpXbW7mXJ0/maxresdefault.jpg",
//     price: 600,
//     originalPrice: 800,
//     discount: 25,
//     stock: 5,
//     expirationDate: "2026-11-20T00:00:00",
//     expiresIn: getDaysUntilExpiration("2026-11-20T00:00:00"),
//     category: "Verdulería",
//     productType: "Frutas",
//     storeId: 3,
//     tags: ["maduro", "vegano", "organico"],
//   },
//   {
//     id: 3,
//     title: "Arroz próximo a vencer",
//     description: "Arroz largo fino de excelente calidad. Fecha de vencimiento próxima pero producto en perfectas condiciones.",
//     imageUrl: "https://static.cotodigital3.com.ar/sitios/fotos/large/00571900/00571982.jpg",
//     price: 450,
//     originalPrice: 750,
//     discount: 40,
//     stock: 15,
//     expirationDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
//     expiresIn: "5 días",
//     category: "Supermercado",
//     productType: "Granos",
//     storeId: 1,
//     tags: ["vegano", "sin-gluten", "buen-estado"],
//   },
//   {
//     id: 4,
//     title: "Berenjenas un poco marchitas (para guisos)",
//     description: "Berenjenas que presentan signos de maduración pero ideales para cocinar. Perfectas para guisos, berenjenas a la parmesana o escabeche.",
//     imageUrl: "https://media.istockphoto.com/id/1312447033/es/foto/fondo-alimentario-crumpled-berenjena-arrugada-primer-plano-de-verduras.jpg?s=170667a&w=0&k=20&c=d2Ejn6t46mw-81phhv88210qPoZZWq82__NsIXPrN9E=",
//     price: 300,
//     originalPrice: 600,
//     discount: 50,
//     stock: 6,
//     expirationDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
//     expiresIn: "1 día",
//     category: "Verdulería",
//     productType: "Verduras",
//     storeId: 3,
//     tags: ["maduro", "vegano", "sin-gluten"],
//   },
//   {
//     id: 5,
//     title: "Pan de molde del día anterior",
//     description: "Pan de molde lactal del día anterior. Ideal para tostadas, sándwiches o budín de pan. Conserva su frescura.",
//     imageUrl: "https://i.ytimg.com/vi/lgor5tys1Zg/hqdefault.jpg",
//     price: 200,
//     originalPrice: 308,
//     discount: 35,
//     stock: 10,
//     expirationDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
//     expiresIn: "3 días",
//     category: "Panadería",
//     productType: "Pan",
//     storeId: 8,
//     tags: ["buen-estado", "vegetariano"],
//   },
//   {
//     id: 7,
//     title: "Hamburguesas congeladas con empaque dañado",
//     description: "Hamburguesas de carne vacuna congeladas. El empaque exterior está levemente dañado pero el producto mantiene la cadena de frío.",
//     imageUrl: "https://media.falabella.com/tottusCL/21082365_1/w=800,h=800,fit=pad",
//     price: 800,
//     originalPrice: 1000,
//     discount: 20,
//     stock: 12,
//     expirationDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
//     expiresIn: "un mes",
//     category: "Supermercado",
//     productType: "Carnes",
//     storeId: 4,
//     tags: ["buen-estado"],
//   },
//   {
//     id: 9,
//     title: "Cereales abiertos parcialmente",
//     description: "Caja de cereales con el empaque exterior parcialmente abierto. Producto sellado interiormente y en perfecto estado.",
//     imageUrl: "https://m.media-amazon.com/images/I/81I9Kt1M7PL._SL1500_.jpg",
//     price: 500,
//     originalPrice: 714,
//     discount: 30,
//     stock: 7,
//     expirationDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
//     expiresIn: "3 semanas",
//     category: "Supermercado",
//     productType: "Desayuno",
//     storeId: 4,
//     tags: ["buen-estado", "vegetariano"],
//   },
//   {
//     id: 11,
//     title: "Facturas del día anterior (panadería)",
//     description: "Facturas surtidas del día anterior. Ideales para desayuno o merienda. Mantienen su sabor y textura.",
//     imageUrl: "https://cocinerosargentinos.com/content/recipes/original/recipes.12842.jpeg",
//     price: 350,
//     originalPrice: 583,
//     discount: 40,
//     stock: 15,
//     expirationDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
//     expiresIn: "1 día",
//     category: "Panadería",
//     productType: "Repostería",
//     storeId: 8,
//     tags: ["buen-estado", "vegetariano"],
//   },
//   {
//     id: 12,
//     title: "Fideos con fecha próxima (supermercado)",
//     description: "Fideos guiseros de excelente marca. Fecha de vencimiento próxima. Producto seco que conserva todas sus propiedades.",
//     imageUrl: "https://jumboargentina.vtexassets.com/arquivos/ids/209822/Fideo-Molto-Guiseros-Fideos-Guisero-Molto-500-Gr-1-46224.jpg?v=636383732923400000",
//     price: 220,
//     originalPrice: 293,
//     discount: 25,
//     stock: 25,
//     expirationDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
//     expiresIn: "10 días",
//     category: "Supermercado",
//     productType: "Pasta",
//     storeId: 1,
//     tags: ["buen-estado", "vegano"],
//   },
//   {
//     id: 13,
//     title: "Ensaladas preparadas para llevar",
//     description: "Ensaladas frescas preparadas en el día. Deben consumirse hoy. Opciones vegetarianas y veganas disponibles.",
//     imageUrl: "https://financialfood.es/wp-content/uploads/2025/03/ALDI_Ensaladas-Daylicious-200325.jpg",
//     price: 700,
//     originalPrice: 824,
//     discount: 15,
//     stock: 4,
//     expirationDate: new Date(Date.now() + 0.5 * 24 * 60 * 60 * 1000).toISOString(),
//     expiresIn: "hoy",
//     category: "Restaurante",
//     productType: "Comida preparada",
//     storeId: 7,
//     tags: ["vegano", "sin-gluten", "buen-estado"],
//   },
//   {
//     id: 14,
//     title: "Tomate para salsa",
//     description: "Tomates perita maduros, perfectos para elaborar salsas, conservas o concentrado. Producto fresco de huerta.",
//     imageUrl: "https://thumbs.dreamstime.com/b/puesto-de-verduler%C3%ADa-con-tomates-diferentes-clases-cajas-llenas-maduros-en-el-verduras-todo-tipo-como-los-cerezo-para-satisfacer-251061069.jpg",
//     price: 280,
//     originalPrice: 431,
//     discount: 35,
//     stock: 10,
//     expirationDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
//     expiresIn: "2 días",
//     category: "Verdulería",
//     productType: "Verduras",
//     storeId: 3,
//     tags: ["maduro", "vegano", "sin-gluten"],
//   },
// ];