import { ProductCategory } from "../enums/product-category.enum";

export const ProductCategoryDisplayName: Record<ProductCategory, string> = {
  [ProductCategory.FRUIT]: "Fruta",
  [ProductCategory.VEGETABLE]: "Verdura",
  [ProductCategory.HERBS]: "Hierbas",
  [ProductCategory.TUBER]: "Tubérculo",
  [ProductCategory.SEEDLING]: "Plantines",
  [ProductCategory.BREAD]: "Pan",
  [ProductCategory.PASTRIES]: "Facturas",
  [ProductCategory.CAKES]: "Tortas",
  [ProductCategory.COOKIES]: "Galletas",
  [ProductCategory.DOUGH]: "Masas",
  [ProductCategory.DESSERTS_BAKERY]: "Postres",
  [ProductCategory.APPETIZERS]: "Entradas",
  [ProductCategory.MAIN_COURSES]: "Platos Principales",
  [ProductCategory.DESSERTS_RESTAURANT]: "Postres",
  [ProductCategory.BEVERAGES_RESTAURANT]: "Bebidas",
  [ProductCategory.CLEANING]: "Limpieza",
  [ProductCategory.BEVERAGES]: "Bebidas",
  [ProductCategory.GROCERIES]: "Comestibles",
  [ProductCategory.FRESH_PRODUCTS]: "Frescos",
  [ProductCategory.FROZEN]: "Congelados",
  [ProductCategory.PERSONAL_HYGIENE]: "Higiene Personal",
  [ProductCategory.CANDY]: "Golosinas",
  [ProductCategory.SNACKS]: "Snacks",
  [ProductCategory.CIGARETTES]: "Cigarrillos",
  [ProductCategory.MAGAZINES]: "Revistas",
  [ProductCategory.GREENGROCERY_SECTION]: "Sección Verdulería (Supermercado)",
  [ProductCategory.BAKERY_SECTION]: "Sección Panadería (Supermercado)",
  [ProductCategory.OTHER]: "Otro",
};
