export const localities: string[] = [
  "Achiras", 
  "Adelia María", 
  "Agua de Oro", 
  "Alcira", 
  "Gigena", 
  "Aldea Santa María", 
  "Alejandro Roca", 
  "Alejo Ledesma", 
  "Alicia", 
  "Almafuerte", 
  "Alpa Corral", 
  "Alta Gracia", 
  "Alto Alegre", 
  "Alto de los Quebrachos", 
  "Altos de Chipión", 
  "Amboy", 
  "Ambul", 
  "Anisacate", 
  "Arias", 
  "Arroyito", 
  "Arroyo Algodón", 
  "Arroyo Cabral", 
  "Assunta", 
  "Atahona", 
  "Ausonia", 
  "Avellaneda", 
  "Ballesteros", 
  "Ballesteros Sud", 
  "Balnearia", 
  "Bañado de Soto", 
  "Bell Ville", 
  "Bengolea", 
  "Benjamín Gould", 
  "Berrotarán", 
  "Bialet Massé", 
  "Bower", 
  "Brinkmann", 
  "Buchardo", 
  "Bulnes", 
  "Cabalango", 
  "Calchín", 
  "Calchín Oeste", 
  "Calmayo", 
  "Camilo Aldao", 
  "Caminiaga", 
  "Canals", 
  "Candelaria Sud", 
  "Capilla del Carmen", 
  "Capilla del Monte", 
  "Capilla de los Remedios", 
  "Capilla de Sitón", 
  "Capitán O’Higgins", 
  "Carrilobo", 
  "Casa Grande", 
  "Cavanagh", 
  "Cañada de Luque", 
  "Cañada de Machado", 
  "Chaján", 
  "Chalacea", 
  "Chancaní", 
  "Charbonier", 
  "Charras", 
  "Chazón", 
  "Chañar Viejo", "Chilibroste", "Churqui Cañada", "Chuña", "Chuña Huasi", "Cintra", "Colazo", "Colonia Almada", "Colonia Anita", "Colonia Bismarck", "Colonia Bremen", "Colonia Caroya", "Colonia Italiana", "Colonia Iturraspe", "Colonia Las Cuatro Esquinas", "Colonia Las Pichanas", "Colonia Prosperidad", "Colonia San Bartolomé", "Colonia San Pedro", "Colonia Tirolesa", "Colonia Valtelina", "Colonia Vicente Aguero", "Colonia Videla", "Colonia Vignaud", "Comechingones", "Conlara", "Copacabana", "Coronel Baigorria", "Coronel Moldes", "Corral de Bustos", "Corralito", "Cosquín", "Costa Sacate", "Cruz Alta", "Cruz de Caña", "Cruz del Eje", "Cuesta Blanca", "Córdoba", "Dalmacio Vélez Sarsfield", "Del Campillo", "Despeñaderos", "Devoto", "Deán Funes", "Dique Chico", "El Arañado", "El Brete", "El Chacho", "El Crispín", "Elena", "El Fortín", "El Manzano", "El Rodeo", "El Tío", "Embalse", "Estación General Paz", "Estación Juárez Célman", "Estancia de Guadalupe", "Estancia Vieja", "Etruria", "Eufrasio Loza", "Falda del Carmen", "Freyre", "General Baldissera", "General Cabrera", "General Dehesa", "General Fotheringham", "General Levalle", "General Roca", "Guatimozín", "Hernando", "Huanchilla", "Huerta Grande", "Huinca Renancó", "Idiazabal", "Impira", "Inriville", "Isla Verde", "Italó", "James Craik", "Jesús María", "Jovita", "Juárez Celman", "Justiniano Posse", "La Batea", "Laborde", "Laboulaye", "La Calera", "La Carlota", "La Carolina-El Potosí", "La Cautiva", "La Cesira", "La Cruz", "La Cumbre", "La Cumbrecita", "La Falda", "La Francia", "La Granja", "Laguna Larga", "La Higuera", "La Laguna", "La Paisanita", "La Palestina", "La Pampa", "La Paquita", "La Para", "La Paz", "La Playa", "La Playosa", "La Población", "La Posta", "La Puerta", "La Quinta", "La Rancherita", "La Rinconada", "Las Acequias", "Las Albahacas", "Las Arrias", "Las Bajadas", "Las Caleras", "Las Calles", "Las Cañadas", "La Serranita", "Las Gramillas", "Las Higueras", "Las Isletillas", "Las Junturas", "Las Perdices", "Las Peñas", "Las Peñas Sud", "Las Playas", "Las Rabonas", "Las Saladas", "Las Tapias", "Las Varas", "Las Varillas", "Las Vertientes", "La Tordilla", "Leguizamón", "Leones", "Los Cedros", "Los Cerrillos", "Los Chañaritos", "Los Cisnes", "Los Cocos", "Los Cóndores", "Los Hornillos", "Los Hoyos", "Los Mistoles", "Los Pozos", "Los Reartes", "Los Surgentes", "Los Talares", "Los Zorros", "Lozada", "Luca", "Lucio V. Mansilla", "Luque", "Lutti", "Luyaba", "Malagueño", "Malena", "Malvinas Argentinas", "Manfredi", "Marcos Juárez", "Marull", "Matorrales", "Mayú Sumaj", "Media Naranja", "Melo", "Mendiolaza", "Mina Clavero", "Miramar", "Monte Buey", "Monte Cristo", "Monte de los Gauchos", "Monte Leña", "Monte Maíz", "Monte Ralo", "Morrison", "Morteros", "Nicolás Bruzzone", "Noetinger", "Nono", "Obispo Trejo", "Olaeta", "Oliva", "Olivares San Nicolás", "Onagoyti", "Oncativo", "Ordoñez", "Pacheco de Melo", "Pampayasta Norte", "Pampayasta Sud", "Panaholma", "Pascanas", "Pasco", "Paso del Durazno", "Paso Viejo", "Pedro Vivas-Km 658", "Pilar", "Pincén", "Piquilín", "Plaza de Mercedes", "Plaza Luxardo", "Porteña", "Potrero de Garay", "Pozo del Molle", "Pozo Nuevo", "Pueblo Italiano", "Punta del Agua", "Quebracho Herrado", "Quilino", "Rafael García", "Ranqueles", "Rayo Cortado", "Reducción", "Rincón", "Rosales", "Río Bamba", "Río Ceballos", "Río Cuarto", "Río de los Sauces", "Río Primero", "Río Segundo", "Río Tercero", "Sacanta", "Sagrada Familia", "Saira", "Saladillo", "Saldán", "Salsacate", "Salsipuedes", "Sampacho", "San Antonio de Arredondo", "San Antonio de Litín", "San Basilio", "San Carlos Minas", "San Clemente", "San Esteban", "San Francisco", "San Francisco del Chañar", "San Gerónimo", "San Javier y Yacanto", "San Joaquín", "San José", "San José de la Dormida", "San José de las Salinas", "San Lorenzo", "San Marcos Sierras", "San Marcos Sud", "San Pedro", "San Pedro Norte", "Santa Catalina-Holmberg", "Santa Eufemia", "Santa María de Punilla", "Santa Rosa de Calamuchita", "Santiago Temple", "Saturnino María Laspiur", "Sauce Arriba", "Sebastián Elcano", "Seeber", "Segunda Usina", "Serrano", "Serrezuela", "Silvio Pellico", "Simbolar", "Sinsacate", "Suco", "Tala Cañada", "Tala Huasi", "Talaini", "Tancacha", "Tanti", "Ticino", "Tinoco", "Tío Pujio", "Toledo", "Tosno", "Tosquita", "Tránsito", "Tuclame", "Ucacha", "Unquillo", "Valle Hermoso", "Viamonte", "Vicuña Mackenna", "Villa Allende", "Villa Amancay", "Villa Ascasubi", "Villa Candelaria", "Villa Carlos Paz", "Villa Cañada del Sauce", "Villa Ciudad de América", "Villa Concepción del Tío", "Villa Cura Brochero", "Villa de las Rosas", "Villa del Dique", "Villa de Los Patos", "Villa del Prado", "Villa del Rosario", "Villa del Totoral", "Villa de María de Río Seco", "Villa de Pocho", "Villa de Soto", "Villa Dolores", "Villa El Chacay", "Villa Fontana", "Villa General Belgrano", "Villa Giardino", "Villa Gutiérrez", "Villa Huidobro", "Villa La Bolsa", "Villa Los Aromos", "Villa María", "Villa Nueva", "Villa Parque Santa Ana", "Villa Quillinzo", "Villa Rossi", "Villa Rumipal", "Villa Río Icho Cruz", "Villa San Esteban", "Villa San Isidro", "Villa Santa Cruz del Lago", "Villa Santa Rosa", "Villa Sarmiento", "Villa Tulumba", "Villa Valeria", "Villa Yacanto", "Washington", "Wenceslao Escalante"
];